package com.example.androidnote.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.androidnote.model.UserInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFO".
*/
public class UserInfoDao extends AbstractDao<UserInfo, Long> {

    public static final String TABLENAME = "USER_INFO";

    /**
     * Properties of entity UserInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ImageFilePath = new Property(1, String.class, "imageFilePath", false, "IMAGE_FILE_PATH");
        public final static Property UserName = new Property(2, String.class, "userName", false, "USER_NAME");
        public final static Property Sex = new Property(3, boolean.class, "sex", false, "SEX");
        public final static Property Desc = new Property(4, String.class, "desc", false, "DESC");
        public final static Property Age = new Property(5, int.class, "age", false, "AGE");
        public final static Property Birthday = new Property(6, String.class, "birthday", false, "BIRTHDAY");
        public final static Property Constellation = new Property(7, String.class, "constellation", false, "CONSTELLATION");
        public final static Property Hobby = new Property(8, String.class, "hobby", false, "HOBBY");
    }


    public UserInfoDao(DaoConfig config) {
        super(config);
    }
    
    public UserInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"IMAGE_FILE_PATH\" TEXT," + // 1: imageFilePath
                "\"USER_NAME\" TEXT NOT NULL ," + // 2: userName
                "\"SEX\" INTEGER NOT NULL ," + // 3: sex
                "\"DESC\" TEXT," + // 4: desc
                "\"AGE\" INTEGER NOT NULL ," + // 5: age
                "\"BIRTHDAY\" TEXT," + // 6: birthday
                "\"CONSTELLATION\" TEXT," + // 7: constellation
                "\"HOBBY\" TEXT);"); // 8: hobby
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String imageFilePath = entity.getImageFilePath();
        if (imageFilePath != null) {
            stmt.bindString(2, imageFilePath);
        }
        stmt.bindString(3, entity.getUserName());
        stmt.bindLong(4, entity.getSex() ? 1L: 0L);
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(5, desc);
        }
        stmt.bindLong(6, entity.getAge());
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(7, birthday);
        }
 
        String constellation = entity.getConstellation();
        if (constellation != null) {
            stmt.bindString(8, constellation);
        }
 
        String hobby = entity.getHobby();
        if (hobby != null) {
            stmt.bindString(9, hobby);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String imageFilePath = entity.getImageFilePath();
        if (imageFilePath != null) {
            stmt.bindString(2, imageFilePath);
        }
        stmt.bindString(3, entity.getUserName());
        stmt.bindLong(4, entity.getSex() ? 1L: 0L);
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(5, desc);
        }
        stmt.bindLong(6, entity.getAge());
 
        String birthday = entity.getBirthday();
        if (birthday != null) {
            stmt.bindString(7, birthday);
        }
 
        String constellation = entity.getConstellation();
        if (constellation != null) {
            stmt.bindString(8, constellation);
        }
 
        String hobby = entity.getHobby();
        if (hobby != null) {
            stmt.bindString(9, hobby);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserInfo readEntity(Cursor cursor, int offset) {
        UserInfo entity = new UserInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // imageFilePath
            cursor.getString(offset + 2), // userName
            cursor.getShort(offset + 3) != 0, // sex
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // desc
            cursor.getInt(offset + 5), // age
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // birthday
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // constellation
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8) // hobby
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setImageFilePath(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserName(cursor.getString(offset + 2));
        entity.setSex(cursor.getShort(offset + 3) != 0);
        entity.setDesc(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAge(cursor.getInt(offset + 5));
        entity.setBirthday(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setConstellation(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setHobby(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
